version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules  

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules 
    environment:
      - DB_USER=johndoe
      - DB_PASSWORD=johndoe123
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=atac_teste
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: johndoe123
      POSTGRES_DB: atac_teste
    ports:
      - "5500:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
